//------------------------------------------------------------------------------
// <auto-generated>
//     此代码由工具生成。
//     运行时版本:4.0.30319.42000
//
//     对此文件的更改可能会导致不正确的行为，并且如果
//     重新生成代码，这些更改将会丢失。
// </auto-generated>
//------------------------------------------------------------------------------

namespace OfficeAuto {
    using System;
    
    
    /// <summary>
    ///   一个强类型的资源类，用于查找本地化的字符串等。
    /// </summary>
    // 此类是由 StronglyTypedResourceBuilder
    // 类通过类似于 ResGen 或 Visual Studio 的工具自动生成的。
    // 若要添加或移除成员，请编辑 .ResX 文件，然后重新运行 ResGen
    // (以 /str 作为命令选项)，或重新生成 VS 项目。
    [global::System.CodeDom.Compiler.GeneratedCodeAttribute("System.Resources.Tools.StronglyTypedResourceBuilder", "4.0.0.0")]
    [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
    [global::System.Runtime.CompilerServices.CompilerGeneratedAttribute()]
    internal class Resource {
        
        private static global::System.Resources.ResourceManager resourceMan;
        
        private static global::System.Globalization.CultureInfo resourceCulture;
        
        [global::System.Diagnostics.CodeAnalysis.SuppressMessageAttribute("Microsoft.Performance", "CA1811:AvoidUncalledPrivateCode")]
        internal Resource() {
        }
        
        /// <summary>
        ///   返回此类使用的缓存的 ResourceManager 实例。
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        internal static global::System.Resources.ResourceManager ResourceManager {
            get {
                if (object.ReferenceEquals(resourceMan, null)) {
                    global::System.Resources.ResourceManager temp = new global::System.Resources.ResourceManager("OfficeAuto.Resource", typeof(Resource).Assembly);
                    resourceMan = temp;
                }
                return resourceMan;
            }
        }
        
        /// <summary>
        ///   使用此强类型资源类，为所有资源查找
        ///   重写当前线程的 CurrentUICulture 属性。
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        internal static global::System.Globalization.CultureInfo Culture {
            get {
                return resourceCulture;
            }
            set {
                resourceCulture = value;
            }
        }
        
        /// <summary>
        ///   查找类似 4 的本地化字符串。
        /// </summary>
        internal static string AmConferenceNum {
            get {
                return ResourceManager.GetString("AmConferenceNum", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 12 的本地化字符串。
        /// </summary>
        internal static string AmEnd {
            get {
                return ResourceManager.GetString("AmEnd", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 8 的本地化字符串。
        /// </summary>
        internal static string AmStart {
            get {
                return ResourceManager.GetString("AmStart", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 &lt;img src=&quot;/OfficeAuto/CusStyle/images_conference/date.png&quot; title=&apos;已被&quot;{0}&quot;会议占用&apos; width=&quot;24&quot; height=&quot;24&quot; align=&quot;absmiddle&quot; onclick=&quot;LinkToView(&apos;{1}&apos;);&quot;/&gt; 的本地化字符串。
        /// </summary>
        internal static string ConferenceOccupy {
            get {
                return ResourceManager.GetString("ConferenceOccupy", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 &lt;img src=&quot;/OfficeAuto/CusStyle/images_conference/add.png&quot; width=&quot;24&quot; height=&quot;24&quot; align=&quot;absmiddle&quot; onclick=&quot;LinkToThis(&apos;{0}&apos;,&apos;{1}&apos;,&apos;{2}&apos;);&quot;/&gt; 的本地化字符串。
        /// </summary>
        internal static string ConferenceUnOccupy {
            get {
                return ResourceManager.GetString("ConferenceUnOccupy", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 2 的本地化字符串。
        /// </summary>
        internal static string Limit {
            get {
                return ResourceManager.GetString("Limit", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 &lt;tr&gt;&lt;td align=&quot;center&quot; class=&quot;bm-grid-celll&quot;&gt;{0}&lt;/td&gt;&lt;td align=&quot;center&quot; valign=&quot;middle&quot; class=&quot;bm-grid-cellf &quot;&gt;{1}&lt;/td&gt;&lt;td align=&quot;center&quot; valign=&quot;middle&quot; class=&quot;bm-grid-cellf &quot;&gt;{2}&lt;/td&gt;&lt;td align=&quot;center&quot; valign=&quot;middle&quot; class=&quot;bm-grid-cellf &quot;&gt;{3}&lt;/td&gt;&lt;td align=&quot;center&quot; valign=&quot;middle&quot; class=&quot;bm-grid-cellf &quot;&gt;{4}&lt;/td&gt;&lt;td align=&quot;center&quot; valign=&quot;middle&quot; class=&quot;bm-grid-cellf &quot;&gt;{5}&lt;/td&gt;&lt;td align=&quot;center&quot; valign=&quot;middle&quot; class=&quot;bm-grid-cellf &quot;&gt;{6}&lt;/td&gt;&lt;td align=&quot;center&quot; valign=&quot;middle&quot; class=&quot;bm-grid-cellf &quot;&gt;{7}&lt;/ [字符串的其余部分被截断]&quot;; 的本地化字符串。
        /// </summary>
        internal static string MeetingBody {
            get {
                return ResourceManager.GetString("MeetingBody", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 4 的本地化字符串。
        /// </summary>
        internal static string PmConferenceNum {
            get {
                return ResourceManager.GetString("PmConferenceNum", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 18 的本地化字符串。
        /// </summary>
        internal static string PmEnd {
            get {
                return ResourceManager.GetString("PmEnd", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 12 的本地化字符串。
        /// </summary>
        internal static string PmStart {
            get {
                return ResourceManager.GetString("PmStart", resourceCulture);
            }
        }
    }
}
